<p align="center">
<FONT FACE="times new roman" SIZE=5>
<br>
<img src="https://res-5.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/v1455514364/pim02bzqvgz0hibsra41.png"
width="250" height="250">
</img>
<br>
<i><b>Docente:</b> Juan Pablo Ospina Lopez.</i>
<br>
<i><b>Asignatura:</b> Inteligencia Artificial</i>
<br>
<i><b>Estudiante:</b> Chiara Vivian Valenzuela Losada</i>
<br>
<i><b>Tema:</b> Laboratorio 4. Introducción a ML.</i>
<br>
<i>11/09/2023</i>
</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

# **Capítulo de cosmos**

Vea el capítulo de cosmos sobre Johannes Kepler. ¿Existe alguna relación con la manera como se realizan los proyectos de aprendizaje automático en este momento? ¿Qué diferencias existen?

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

**Relación con proyectos de aprendizaje automático:**

- *Uso de datos y observación:* Kepler recopiló observaciones detalladas de los movimientos planetarios a lo largo del tiempo. De manera similar, los proyectos de aprendizaje automático a menudo se basan en la recopilación y el análisis de grandes conjuntos de datos para extraer patrones y hacer predicciones.

- *Modelado matemático:* Kepler desarrolló leyes matemáticas precisas que describen el movimiento de los planetas. En el aprendizaje automático, se utilizan modelos matemáticos y algoritmos para entrenar sistemas que pueden aprender de los datos y tomar decisiones.

- *Generalización y predicción:* Kepler utilizó sus leyes para hacer predicciones precisas sobre la posición futura de los planetas. En el aprendizaje automático, los modelos se entrenan para generalizar a partir de datos existentes y realizar predicciones sobre datos nuevos o desconocidos.

**Diferencias con proyectos de aprendizaje automático:**

* *Naturaleza de los datos:* Kepler trabajó con datos astronómicos recopilados manualmente a lo largo de décadas. En contraste, los proyectos de aprendizaje automático a menudo se basan en datos digitales masivos y en tiempo real, y pueden aprovechar tecnologías como sensores y cámaras.

- *Tamaño y complejidad de los modelos:* Kepler utilizó ecuaciones matemáticas relativamente simples para describir el movimiento planetario. En el aprendizaje automático, los modelos pueden ser extremadamente complejos y pueden involucrar redes neuronales profundas con millones de parámetros.

- *Objetivos diferentes:* Kepler estaba interesado en comprender los movimientos planetarios y el sistema solar. En contraste, los proyectos de aprendizaje automático tienen una variedad de aplicaciones, que van desde la detección de fraudes hasta la recomendación de películas.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

# **Diferencias y similitudes**

¿Qué diferencias y similitudes existen entre la ciencia de datos, el Big data, el aprendizaje de máquina, la estadística, inteligencia artificial y aprendizaje profundo?

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

### **Similitudes:**

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

1. **Enfoque en Datos:** Todos estos campos se centran en el análisis y procesamiento de datos para obtener información valiosa y tomar decisiones informadas.

2. **Matemáticas y Estadísticas:** La matemática y la estadística desempeñan un papel fundamental en cada uno de estos campos para modelar y analizar datos.

3. **Aplicaciones Prácticas:** Se aplican en una amplia variedad de aplicaciones prácticas en campos como la medicina, el comercio electrónico, la robótica, la ingeniería, la seguridad cibernética y más.

4. **Interdisciplinarios:** Todos estos campos son interdisciplinarios y requieren conocimientos de diversas áreas, como matemáticas, informática, estadísticas y dominio del problema.

5. **Tecnología y Herramientas:** Dependen en gran medida de la tecnología y herramientas avanzadas para manejar y analizar grandes volúmenes de datos.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

### **Diferencias**


</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

**Definición y Objetivos:**

- La ciencia de datos se centra en el proceso completo de análisis de datos, desde la adquisición hasta la toma de decisiones.
- El Big Data se enfoca principalmente en el manejo de grandes conjuntos de datos, con énfasis en la infraestructura y el procesamiento.
- El aprendizaje de máquina se refiere a la construcción de modelos que pueden aprender y tomar decisiones basadas en datos.
- La estadística es una disciplina que se ocupa del análisis de datos y la inferencia.
- La inteligencia artificial busca crear sistemas que puedan realizar tareas inteligentes sin ser programados explícitamente.
- El aprendizaje profundo es una subdisciplina del aprendizaje de máquina que utiliza redes neuronales profundas para modelar datos.


**Escalabilidad de Datos:**

- La ciencia de datos puede trabajar con datos de cualquier tamaño y no está limitada por la escala.
- El Big Data se enfoca en el manejo de grandes volúmenes de datos que pueden ser petabytes o más.
- El aprendizaje de máquina puede trabajar con datos pequeños o grandes y es escalable.
- La estadística no está limitada por la escala de datos.
- La inteligencia artificial puede trabajar con datos pequeños o grandes y es escalable.
- El aprendizaje profundo a menudo requiere grandes cantidades de datos y potencia de cómputo.

**Requerimientos de Datos y Recursos:**

- El Big Data generalmente requiere infraestructura robusta para manejar grandes conjuntos de datos y recursos de almacenamiento y procesamiento escalables.
- El aprendizaje profundo suele requerir grandes conjuntos de datos etiquetados y recursos de cómputo de alto rendimiento, como GPU.


</FONT>
</p>

<p align="center">
<FONT FACE="times new roman" SIZE=5>

| Aspecto               | Ciencia de Datos    | Big Data            | Aprendizaje de Máquina | Estadística        | Inteligencia Artificial | Aprendizaje Profundo |
|-----------------------|---------------------|---------------------|-------------------------|---------------------|-------------------------|-----------------------|
| **Enfoque Principal** | Análisis de datos, obtención de insights y toma de decisiones basadas en datos. | Gestión y procesamiento de datos a gran escala, incluyendo almacenamiento distribuido y técnicas de procesamiento. | Entrenamiento de modelos para predicción y toma de decisiones automatizadas. | Análisis y modelado estadístico para inferir conclusiones. | Automatización de tareas inteligentes y razonamiento lógico. | Modelado complejo con redes neuronales profundas. |
| **Técnicas Comunes**  | Minería de datos, visualización, estadísticas descriptivas. | Almacenamiento distribuido, procesamiento en clústeres, técnicas de procesamiento masivo. | Regresión, clasificación, agrupamiento, redes neuronales, árboles de decisión, SVM. | Pruebas de hipótesis, análisis de varianza, regresión lineal, métodos estadísticos. | Algoritmos de aprendizaje supervisado y no supervisado, redes bayesianas. | Redes neuronales convolucionales (CNN), redes neuronales recurrentes (RNN), GAN. |
| **Ejemplos de Aplicación** | Análisis de mercado, recomendación de productos, análisis de redes sociales. | Análisis de registros de transacciones, análisis de redes sociales a gran escala. | Reconocimiento de voz, detección de spam, diagnóstico médico asistido por computadora. | Estudios clínicos, análisis de encuestas, control de calidad. | Asistentes virtuales, chatbots, visión por computadora. | Reconocimiento de imágenes, procesamiento de lenguaje natural, conducción autónoma. |

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

# **Hypothesis vs Data Driven Science**

Lea el artículo titulado: Hypothesis vs Data Driven Science e identifique al menos 4 ideas que le parezcan significativas

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

1. La realidad posee una estructura jerárquica similar a una pirámide, gobernada desde arriba por unas pocas leyes profundas de alto nivel y manifestada en su máxima complejidad en el nivel fenomenológico más bajo.

2. Hay dos estrategias que se pueden emplear para modelar los fenómenos: buscar lo simple o acumular suficientes datos fenomenológicos y dejar que las máquinas hagan el trabajo rutinario.

3. La ciencia impulsada por hipótesis tiene una dirección desde el principio, lo que hace que las sorpresas sean difíciles de encontrar, a menos que se tengan capacidades de intuición excepcionalmente creativas.

4. Los modelos computacionales de aprendizaje automático pueden predecir los pliegues de proteínas con mayor precisión que los investigadores humanos, lo que lleva a algunos a lamentar la pérdida de la teoría sobre los datos.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

# **Científico de datos, un analista de datos y un ingeniero**

¿En qué se diferencia un científico de datos, un analista de datos y un ingeniero de machine learning?

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

*Científico de Datos (Data Scientist):*

1. **Enfoque Principal:** Los científicos de datos tienen un enfoque amplio que abarca todo el ciclo de vida de los datos, desde la recopilación y limpieza hasta la modelización y la comunicación de resultados. Se centran en la generación de conocimiento a partir de los datos.

2. **Responsabilidades Típicas:**
   - Recopilación y limpieza de datos.
   - Análisis exploratorio de datos.
   - Desarrollo de modelos de aprendizaje de máquina.
   - Evaluación y selección de modelos.
   - Comunicación de resultados a partes interesadas.

3. **Habilidades Requeridas:** Los científicos de datos deben tener habilidades en programación (por ejemplo, Python o R), estadísticas, aprendizaje de máquina, visualización de datos y comunicación. También necesitan conocimientos de dominio para comprender el contexto de los datos.

4. **Objetivo Final:** Su objetivo final es utilizar datos para generar insights, pronosticar tendencias y tomar decisiones informadas en una variedad de campos.

*Analista de Datos (Data Analyst):*

1. **Enfoque Principal:** Los analistas de datos se centran en analizar datos existentes para responder preguntas específicas y proporcionar información que respalde la toma de decisiones.

2. **Responsabilidades Típicas:**
   - Recopilación y limpieza de datos.
   - Análisis estadístico y exploratorio de datos.
   - Creación de informes y visualizaciones de datos.
   - Identificación de tendencias y patrones.

3. **Habilidades Requeridas:** Los analistas de datos necesitan habilidades en estadísticas, análisis de datos y herramientas de visualización (como Excel o herramientas de Business Intelligence). También pueden utilizar SQL para consultas de bases de datos.

4. **Objetivo Final:** Su objetivo final es proporcionar información que respalde la toma de decisiones en un contexto específico utilizando datos existentes.

*Ingeniero de Machine Learning (Machine Learning Engineer):*

1. **Enfoque Principal:** Los ingenieros de machine learning se centran en el desarrollo y la implementación de sistemas de aprendizaje de máquina en producción.

2. **Responsabilidades Típicas:**
   - Construcción y optimización de modelos de aprendizaje de máquina.
   - Implementación de modelos en aplicaciones y sistemas.
   - Automatización de flujos de trabajo de aprendizaje de máquina.
   - Mantenimiento y escalabilidad de sistemas de machine learning.

3. **Habilidades Requeridas:** Los ingenieros de machine learning necesitan habilidades en programación (generalmente en lenguajes como Python o Java), experiencia en aprendizaje de máquina, implementación de modelos en producción y conocimientos de ingeniería de software.

4. **Objetivo Final:** Su objetivo final es desarrollar sistemas de machine learning que funcionen en la vida real y puedan tomar decisiones automatizadas basadas en datos.

En resumen, los científicos de datos se centran en la generación de conocimiento a partir de los datos, los analistas de datos se enfocan en el análisis de datos existentes para respaldar decisiones, y los ingenieros de machine learning desarrollan sistemas de machine learning para la implementación en aplicaciones y sistemas en producción. Cada uno de estos roles desempeña un papel esencial en el campo de los datos y el aprendizaje de máquina.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

# **Científico de datos para la alcaldía de Bogotá**

Suponga que usted trabaja como científico de datos para la alcaldía de Bogotá. Proponga al menos 3 problemáticas que puedan ser abordadas utilizando técnicas de aprendizaje supervisado.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman">

1. **Predicción de Accidentes de Tráfico:** Utilizando datos históricos de accidentes de tráfico, condiciones meteorológicas, congestión del tráfico y otros factores relevantes, se podría construir un modelo de aprendizaje supervisado para predecir la probabilidad de que ocurran accidentes en diferentes áreas de la ciudad en función de las condiciones actuales. Esto permitiría a la alcaldía tomar medidas proactivas para reducir los accidentes y mejorar la seguridad vial.

2. **Detección y Predicción de Contaminación del Aire:** Bogotá enfrenta desafíos relacionados con la calidad del aire debido al tráfico y otras fuentes de contaminación. Un modelo de aprendizaje supervisado podría utilizar datos históricos de calidad del aire, datos meteorológicos, tráfico y otros factores para predecir niveles de contaminación futuros. Esto ayudaría a la alcaldía a implementar políticas y medidas de mitigación en áreas con mayor riesgo de contaminación.

3. **Predicción de Demanda de Transporte Público:** Mediante el uso de datos de uso del transporte público, demografía, eventos especiales y horarios, se podría desarrollar un modelo de aprendizaje supervisado para predecir la demanda en diferentes rutas y momentos del día. Esto permitiría una mejor planificación de la capacidad y la eficiencia del sistema.

4. **Predicción de Inundaciones:** Utilizando datos históricos de lluvias, niveles de ríos, topografía y datos de sensores ambientales, se podría desarrollar un modelo de aprendizaje supervisado para predecir el riesgo de inundaciones en diferentes áreas de la ciudad. Esto ayudaría en la planificación de medidas de prevención y evacuación durante condiciones climáticas extremas.

</FONT>
</p>

<p align="center">
<FONT FACE="times new roman" SIZE=5>

# **Ejercicios de Numpy**

Realice los ejercicios de Numpy propuestos en el archivo adjunto.

</FONT>
</p>

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


## __Creando Arreglos__

Genere un arreglo de tamaño 10 lleno de ceros

In [ ]:
arreglo_de_ceros = np.zeros(10)
print(arreglo_de_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Genere un arreglo con valores del 10 al 49

In [ ]:
arreglo_valores = np.arange(10, 50)
print(arreglo_valores)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Genere una matriz de $4 \times 4$ con valores enteros llena de unos

In [ ]:
matriz_de_unos = np.ones((4, 4), dtype=int)
print(matriz_de_unos)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Genere una matriz de $ 2 \times 2$ con valores flotantes llena de unos

In [ ]:
matriz_de_unos = np.ones((2, 2), dtype=float)
print(matriz_de_unos)

[[1. 1.]
 [1. 1.]]


Genere una matriz de  $ 3 \times 4$ con valores enteros llena de cincos

In [ ]:
matriz_de_cincos = 5 * np.ones((3, 4), dtype=int)
print(matriz_de_cincos)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Genere una matriz identidad de $ 3 \times 3$

In [ ]:
matriz_identidad = np.eye(3, dtype=int)
print(matriz_identidad)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Genere una matriz de $ 3 \times 4$ con valores aleatorios entre cero y uno

In [ ]:
matriz_aleatoria = np.random.rand(3, 4)
print(matriz_aleatoria)

[[0.18423768 0.7834237  0.76538862 0.17133679]
 [0.74207321 0.83213301 0.73851002 0.56911717]
 [0.25500464 0.02819841 0.40115018 0.75898824]]


## __Manipulando índices__

Para el siguiente arreglo imprima el primer elemento

In [ ]:
X = np.array(['A','B','C','D','E'])
print(X[0])

A


Para el siguiente arreglo imprima  el primer y el último elemento

In [ ]:
X = np.array(['A','B','C','D','E'])
print("Primer elemento:", X[0])
print("Último elemento:", X[-1])

Primer elemento: A
Último elemento: E


Para el siguiente arreglo imprima los primeros tres elementos

In [ ]:
X = np.array(['A','B','C','D','E'])
primeros_tres_elementos = X[:3]
print("Primeros tres elementos:", primeros_tres_elementos)

Primeros tres elementos: ['A' 'B' 'C']


Para el siguiente arreglo imprima todos los elementos menos el primero y el último

In [ ]:
X = np.array(['A','B','C','D','E'])
elementos_intermedios = X[1:-1]

print("Elementos intermedios:", elementos_intermedios)

Elementos intermedios: ['B' 'C' 'D']


Para el siguiente arreglo imprima todos los elementos en orden inverso

In [ ]:
X = np.array(['A','B','C','D','E'])
elementos_en_inverso = X[::-1]

print("Elementos en orden inverso:", elementos_en_inverso)

Elementos en orden inverso: ['E' 'D' 'C' 'B' 'A']


Para el siguiente arreglo imprima todos los elementos en posiciones pares

In [ ]:
X = np.array(['A','B','C','D','E'])
elementos_en_posiciones_pares = X[::2]

print("Elementos en posiciones pares:", elementos_en_posiciones_pares)

Elementos en posiciones pares: ['A' 'C' 'E']


Para la siguiente matriz imprima la primera columna

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
primera_columna = X[:, 0]

print("Primera columna:", primera_columna)

Primera columna: [ 1  5  9 13]


Para la siguiente matriz imprima la última fila

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
ultima_fila = X[-1, :]

print("Última fila:", ultima_fila)

Última fila: [13 14 15 16]


Para la siguiente matriz imprima el primer elemento de la segunda columna

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
primer_elemento_segunda_columna = X[0, 1]

print("Primer elemento de la segunda columna:", primer_elemento_segunda_columna)

Primer elemento de la segunda columna: 2


Para la siguiente matriz imprima los primeros dos elementos de las dos primeras filas

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
elementos_primeras_dos_filas = X[:2, :2]  # Accede a los primeros dos elementos de las dos primeras filas

print("Primeros dos elementos de las dos primeras filas:")
print(elementos_primeras_dos_filas)

Primeros dos elementos de las dos primeras filas:
[[1 2]
 [5 6]]


Para la siguiente matriz imprima los últimos dos elementos de las últimas dos filas

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
elementos_ultimas_dos_filas = X[-2:, -2:]  # Accede a los últimos dos elementos de las últimas dos filas

print("Últimos dos elementos de las últimas dos filas:")
print(elementos_ultimas_dos_filas)

Últimos dos elementos de las últimas dos filas:
[[11 12]
 [15 16]]


## __Modificando Arreglos__

Convierta la siguiente lista a un arreglo de NumPy de tipo flotante

In [ ]:
X = [-5, -3, 0, 10, 40]
arreglo_np = np.array(X, dtype=float)

print(arreglo_np)

[-5. -3.  0. 10. 40.]


Para el siguiente arreglo establezca el tercer elemento como 10


In [ ]:
X = np.array([10, 20, 30, 50])
X[2] = 10

print(X)

[10 20 10 50]


Para la siguiente matriz cambie todos los valores de la última fila a unos

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1, :] = np.ones(X.shape[1], dtype=int)

print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


Para la siguiente matriz cambie el último elemento de la última fila a cero

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1, -1] = 0

print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


Dada la siguiente matriz sume 5 unidades a cada elemento

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X += 5

print(X)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


## __Arreglos Booleanos__

Para el siguiente arreglo imprima únicamente los valores negativos

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
valores_negativos = X[X < 0]

print("Valores negativos:", valores_negativos)

Valores negativos: [-1 -4 -9]


Parael siguiente arreglo imprima todos los valores mayores a 5

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
valores_mayores_a_5 = X[X > 5]

print("Valores mayores a 5:", valores_mayores_a_5)

Valores mayores a 5: [ 6 10]


Para el siguiente arreglo imprima todos los valores mayores o iguales a la media

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
media = np.mean(X)
valores_mayores_o_iguales_a_media = X[X >= media]

print("Media", media)
print("Valores mayores o iguales a la media:", valores_mayores_o_iguales_a_media)

Media 0.9
Valores mayores o iguales a la media: [ 2  5  6 10]


Para el siguiente arreglo imprima todos los valores iguales a dos o a 10

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
valores_iguales_a_2_o_10 = X[(X == 2) | (X == 10)]

print("Valores iguales a 2 o a 10:", valores_iguales_a_2_o_10)

Valores iguales a 2 o a 10: [ 2 10]


Para el siguiente arreglo imprima todos los valores menores a la desviación estándar o mayores a la media.

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
media = np.mean(X)
desviacion_estandar = np.std(X)

valores_seleccionados = (X < desviacion_estandar) | (X > media)

print("Media ",media)
print("Desviación estándar ", desviacion_estandar)
print("Valores menores a la desviación estándar o mayores a la media:", X[valores_seleccionados])

Media  0.9
Desviación estándar  5.048762224545735
Valores menores a la desviación estándar o mayores a la media: [-1  2  0 -4  5  6  0  0 -9 10]


## __Estadísticas__

Para el siguiente arreglo imprima la suma de sus valores

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

print("Suma de los valores en el arreglo X:", np.sum(X))

Suma de los valores en el arreglo X: 37


Para la siguiente matriz imprima la media de sus columnas

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
media_columnas = np.mean(X, axis=0)

print("Media de las columnas de la matriz X:")
print(media_columnas)

Media de las columnas de la matriz X:
[ 7.  8.  9. 10.]


Para la siguiente matriz imprima la suma de sus filas

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
suma_filas = np.sum(X, axis=1)

print("Suma de las filas de la matriz X:")
print(suma_filas)

Suma de las filas de la matriz X:
[10 26 42 58]


Para la siguiente matriz, imprima el valor máximo

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print("Valor máximo de la matriz X:", np.max(X))

Valor máximo de la matriz X: 16
